from aiogram.fsm.state import StatesGroup, State

class UserStates(StatesGroup):
    awaiting_api_key = State()
    awaiting_rating = State()
    awaiting_request = State()
    awaiting_shop_name = State()
    started = State()
    menu = State()
    shop_list = State()
    chosen_to_delete = State()
    balance_menu = State()
    balance_replenishment = State()
    support_menu = State()
    answers_menu = State()
    show_last_answers = State()
    archive = State()
    awaiting_auto_choose = State()
    toggle_auto = State()
    chosen_shop = State()
    unanswered = State()
    generator_is_on = State()
    generated = State()
    editing = State()
    awaiting_publish = State()